### ISSUE TITLE
Pull error

### ISSUE THREAD

**Issue by knkrth** [eazel7/c9v3dashboard#2]
While creating a new instance, I got the following error on the log,

```
serving DNS
Pull err: null
Pull err: null
```

**Comment by knkrth** [comment]
```
Pull err: null
{ Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24 
    at /home/workspace/c9/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: undefined,
  statusCode: 400,
  json:
   { message:
      'starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24' } } undefined
Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24 
    at /home/workspace/c9/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/home/workspace/c9/node_modules/docker-modem/lib/modem.js:232:14)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
